### ISSUE TITLE
Out of Memory Exception

### ISSUE THREAD

**Issue by LukiLeu** [Mostey/loadify#30]
Hi 
I try to read my playlist with your account. Unfortunatly loadify falls into an out of memory exception when it tries to read my playlists. It occurs in the file PlaylistViewModels.cs on line 163. I have 77 playlists.
Do you have an idea how to fix this?
Kind regards
LukiLeu

**Comment by Mostey** [comment]
How much tracks do you got overall? Metadata from every playlist and every track is collected, this data also contains various information about the artists, album covers and much more so there may be a memory leak anywhere in the code that does not release the memory properly after loading it. 

I will look into it and see if I can improve memory management, thanks for reporting this issue. Your fix is more a work around than an actual solution so I won't merge that for now.

**Comment by LukiLeu** [comment]
Hi
All in all there are around 15'150 songs in all of my playlists.

**Comment by Mostey** [comment]
15'150? Do you mean 15.150?

**Comment by LukiLeu** [comment]
Yeah, I mean 15 thousand

**Comment by LukiLeu** [comment]
So I found out that the class "AlbumModel" and "PlaylistModel" are responsible. Especially the two byte[] Arrays for the "Cover" and the "Image" use alone around 1.8 GB of Memory.

**Comment by LukiLeu** [comment]
So I added the minimizing (compression) of the albumcovers. The size stays the same. I couln't detect a visible change of the image (by eye). On the other side the memory consumption is dratically reduced with the proposed change. Also it seems like the garbagecollector is working better now.
![screenshot 2015-03-04 21 41 56](https://cloud.githubusercontent.com/assets/3243291/6493002/c5d75f3e-c2b7-11e4-8462-9ac4dd6590a3.png)
![screenshot 2015-03-04 21 42 23](https://cloud.githubusercontent.com/assets/3243291/6493003/c5dc1bb4-c2b7-11e4-8d56-7114add5ea03.png)

**Comment by Mostey** [comment]
Thank you for you work, though another problem is that the memory being allocated is never released as long  as the application runs which is causing high memory usage. I probably didn't care that much when I wrote that stuff...

I will merge your changes with my future changes if I'm ready with the optimization. The compression will be kept if there's really no (big) difference.

**Comment by Mostey** [comment]
Well, I refactored almost everything that gets or modifies playlists, tracks, albums and artists and I managed to release every resource immediately after using it.

Additionally the playlist and artist cover images are not loaded anymore, this will speed up things and won't affect anything because these images are never used anywhere. I have no idea why I did that in the first place, probably because I wanted to use them for anything view specific,

The album cover won't be retrieved if the playlists and tracks of the account are collected. Instead, it is retrieved only if it is actually needed (i.e. when writing the ID3 cover tag) resulting in muuuuuuuuuuuch better loading times.

You can check out the changes and test it yourself (see the `memory_fix` branch) but be warned: I had to change a lot, there may be some bugs that I didn't encounter so far. In the next days I will have to refactor the download service because it really needs some work, quite messy stuff that I couldn't fix for now.

I also did a few tests and observed the file size with album cover and without album cover, compression shouldn't be that important:
328 kbps, 6:56min duration, without cover => 15,0 mb
328 kbps, 6:56 min duration with cover => 15,1 mb

**Comment by LukiLeu** [comment]
Thank you for your work. Memory consumpation is now good, nothing extraordinary here, so albumcover compression is not needed anymore. Unfortunatly all songs downloaded are silent (no music).

**Comment by Mostey** [comment]
Really? I have no problems with the sound, everything is still working.

**Comment by LukiLeu** [comment]
Sorry my bad, had headphones connected but the computer routed the MediaPlayer and VLC to my stereo which wasn't turned on. The files are generated correctly.

**Comment by Mostey** [comment]
Fine, I will close this for now. As soon as I'm finished with testing and refactoring, the changes will be merged into the master branch. Guess that version 1.1 will be a performance/optimization update without any (big) changes.
